### ISSUE TITLE
unhashable type: 'list' in vgg_normalised_conv5_1

### ISSUE THREAD

**Issue by SolicTous** [Kibeom-Hong/AesPA-Net#8]
`Traceback (most recent call last):
  File "C:\Users\...\AesPA\main.py", line 44, in <module>
    model = Baseline(args)
  File "C:\Users\...\AesPA\baseline.py", line 94, in __init__
    pretrained_vgg = torchfile.load('./baseline_checkpoints/vgg_normalised_conv5_1.t7')
  File "C:\Users\...\venv\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\...\venv\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\...\venv\lib\site-packages\torchfile.py", line 385, in read_obj
    k = self.read_obj()
  File "C:\Users\...\venv\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\...\venv\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\...\venv\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'list'
`

**Comment by SolicTous** [comment]
It works on linux, but do not work on windows.
And my 2070S can't run. So there are needed more than 7 Gb gpu ram. I read paper and saw that was tested on 3090Ti with 24 Gb =D
